# Generated by Django 5.0.14 on 2026-08-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categorias_por_defecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='origen',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('extranjero', 'Extranjero')], max_length=12, verbose_name='Origen'),
        ),
    ]
