# Generated by Django 5.0.14 on 2026-08-06 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('capacidad', models.CharField(blank=True, max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen_url', models.CharField(blank=True, max_length=300)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_optimo', models.PositiveIntegerField(default=20)),
                ('stock_alerta', models.PositiveIntegerField(default=5)),
                ('stock_critico', models.PositiveIntegerField(default=2)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(limit_choices_to={'tipo': 'venta'}, on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='core.bodega')),
                ('categoria', models.ForeignKey(blank=True, limit_choices_to={'modulo': 'ventas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['nombre_producto'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=30)),
                ('tipo_documento', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida')], max_length=10)),
                ('tipo_transaccion', models.CharField(choices=[('venta', 'Venta'), ('prestamo_demo', 'Préstamo / Demo'), ('repuestos', 'Repuestos'), ('materiales_otro', 'Materiales / Otro')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('solicitado_por', models.CharField(blank=True, max_length=150)),
                ('entregado_por', models.CharField(blank=True, max_length=150)),
                ('cliente_nombre', models.CharField(blank=True, max_length=150)),
                ('no_factura', models.CharField(blank=True, max_length=50)),
                ('no_boleta', models.CharField(blank=True, max_length=50)),
                ('envio_recibo', models.CharField(blank=True, max_length=100)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('devuelto_por', models.CharField(blank=True, max_length=150)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='ventas.articulo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_venta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de venta',
                'verbose_name_plural': 'Movimientos de venta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.CheckConstraint(check=models.Q(('stock_critico__lte', models.F('stock_alerta'))), name='chk_critico_lte_alerta'),
        ),
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.CheckConstraint(check=models.Q(('stock_alerta__lte', models.F('stock_optimo'))), name='chk_alerta_lte_optimo'),
        ),
        migrations.AddIndex(
            model_name='movimientoventa',
            index=models.Index(fields=['articulo', 'fecha'], name='ventas_movi_articul_7651d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientoventa',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gt', 0)), name='chk_mov_venta_cantidad_positiva'),
        ),
    ]
