# Generated by Django 5.0.14 on 2026-08-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='URL de imagen (alternativa)'),
        ),
    ]
