# Generated by Django 5.0.14 on 2026-08-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_articulo_imagen_alter_articulo_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
