# Generated by Django 5.0.14 on 2026-08-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_articulo_codigo_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoventa',
            name='tipo_transaccion',
            field=models.CharField(choices=[('venta', 'Venta'), ('prestamo_demo', 'Préstamo / Demo'), ('repuestos', 'Repuestos'), ('materiales_otro', 'Materiales / Otro'), ('ajuste_inicial', 'Ajuste / Saldo inicial')], max_length=20),
        ),
    ]
