# Generated by Django 5.0.14 on 2026-08-20 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_movimientoventa_tipo_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoventa',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimientoventa',
            name='folio',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
