# Generated by Django 5.0.14 on 2026-08-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_proveedor_origen'),
        ('ventas', '0005_alter_movimientoventa_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='articulo',
            name='chk_critico_lte_alerta',
        ),
        migrations.RemoveConstraint(
            model_name='articulo',
            name='chk_alerta_lte_optimo',
        ),
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.CheckConstraint(check=models.Q(('stock_critico__lte', models.F('stock_alerta'))), name='chk_critico_lte_alerta', violation_error_message='Los umbrales deben cumplir: crítico ≤ alerta ≤ óptimo.'),
        ),
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.CheckConstraint(check=models.Q(('stock_alerta__lte', models.F('stock_optimo'))), name='chk_alerta_lte_optimo', violation_error_message='Los umbrales deben cumplir: crítico ≤ alerta ≤ óptimo.'),
        ),
    ]
