# Generated by Django 5.0.14 on 2026-09-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_mensaje_umbrales'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
