# Generated by Django 5.0.14 on 2026-09-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_precio_de_los_movimientos_existentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoventa',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
