# Generated by Django 5.0.14 on 2026-09-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_movimientoventa_precio_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoventa',
            name='no_boleta',
        ),
    ]
