# Generated by Django 5.0.14 on 2026-09-09 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_remove_movimientoventa_no_boleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='numero_serie',
        ),
        migrations.AddField(
            model_name='articulo',
            name='lleva_serie',
            field=models.BooleanField(default=False, help_text='Equipos que se controlan uno por uno por su serial. Los repuestos y consumibles van sin marcar, por cantidad.', verbose_name='Lleva número de serie'),
        ),
        migrations.CreateModel(
            name='UnidadArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='ventas.articulo')),
                ('movimiento_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_ingresadas', to='ventas.movimientoventa')),
                ('movimiento_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades_salidas', to='ventas.movimientoventa')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['numero_serie'],
                'indexes': [models.Index(fields=['articulo', 'movimiento_salida'], name='ventas_unid_articul_047d89_idx')],
            },
        ),
    ]
