# Generated by Django 5.0.14 on 2026-08-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('operador', 'Operador de bodega'), ('contabilidad', 'Contabilidad'), ('practicante', 'Practicante')], default='operador', max_length=20),
        ),
    ]
