# Generated by Django 5.0.14 on 2026-08-06 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen_url', models.CharField(blank=True, max_length=300)),
                ('estado', models.CharField(choices=[('buen_estado', 'Buen estado'), ('mal_estado', 'Mal estado'), ('de_baja', 'De baja')], default='buen_estado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(limit_choices_to={'tipo': 'tecnica'}, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='core.bodega')),
                ('categoria', models.ForeignKey(blank=True, limit_choices_to={'modulo': 'tecnica'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['nombre_producto'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('solicitante', models.CharField(max_length=150)),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('entregado_por', models.CharField(blank=True, max_length=150)),
                ('estado_al_salir', models.CharField(choices=[('buen_estado', 'Buen estado'), ('mal_estado', 'Mal estado')], max_length=20)),
                ('fecha_regreso', models.DateTimeField(blank=True, null=True)),
                ('recibido_por', models.CharField(blank=True, max_length=150)),
                ('estado_al_regresar', models.CharField(blank=True, choices=[('buen_estado', 'Buen estado'), ('mal_estado', 'Mal estado'), ('de_baja', 'De baja')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='tecnica.activo')),
            ],
            options={
                'verbose_name': 'Préstamo de activo',
                'verbose_name_plural': 'Préstamos de activos',
                'ordering': ['-fecha_salida'],
            },
        ),
    ]
