# Generated by Django 5.0.14 on 2026-08-06 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoactivo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='prestamoactivo',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_regreso__isnull', True)), fields=('activo',), name='ux_prestamo_abierto_por_activo'),
        ),
    ]
