# Generated by Django 5.0.14 on 2026-08-20 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnica', '0003_activo_imagen_alter_activo_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamoactivo',
            name='fecha_salida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
