# Generated by Django 5.0.14 on 2026-08-27 21:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categorias_por_defecto'),
        ('tecnica', '0004_alter_prestamoactivo_fecha_salida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, db_index=True, max_length=30)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('baja', 'Baja'), ('ajuste', 'Ajuste de existencia')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('solicitado_por', models.CharField(blank=True, max_length=150)),
                ('no_factura', models.CharField(blank=True, max_length=50)),
                ('no_boleta', models.CharField(blank=True, max_length=50)),
                ('motivo', models.CharField(blank=True, choices=[('danado', 'Dañado / ya no sirve'), ('extraviado', 'Extraviado'), ('consumido', 'Consumido / gastado'), ('otro', 'Otro')], max_length=20)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Bodega Técnica',
                'verbose_name_plural': 'Movimientos de Bodega Técnica',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='prestamoactivo',
            name='ux_prestamo_abierto_por_activo',
        ),
        migrations.AddField(
            model_name='activo',
            name='es_consumible',
            field=models.BooleanField(default=False, help_text='Cosas que se gastan (bombillos, flejes, pintura). Permite corregir la existencia escribiéndola aquí, sin registrar una baja.', verbose_name='Es consumible'),
        ),
        migrations.AddField(
            model_name='activo',
            name='existencia',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('buen_estado', 'Buen estado'), ('mal_estado', 'Mal estado')], default='buen_estado', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamoactivo',
            name='estado_al_regresar',
            field=models.CharField(blank=True, choices=[('buen_estado', 'Buen estado'), ('mal_estado', 'Mal estado')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='prestamoactivo',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gt', 0)), name='chk_prestamo_cantidad_positiva'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='tecnica.activo'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_tecnica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='movimientoactivo',
            index=models.Index(fields=['activo', 'fecha'], name='tecnica_mov_activo__7c1fa4_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientoactivo',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gt', 0)), name='chk_mov_activo_cantidad_positiva'),
        ),
    ]
