# Generated by Django 5.0.14 on 2026-09-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnica', '0006_datos_existencia_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('buen_estado', 'Buen estado'), ('proximo_a_reemplazo', 'Próximo a reemplazo'), ('mal_estado', 'Mal estado')], default='buen_estado', max_length=30),
        ),
        migrations.AlterField(
            model_name='prestamoactivo',
            name='estado_al_regresar',
            field=models.CharField(blank=True, choices=[('buen_estado', 'Buen estado'), ('proximo_a_reemplazo', 'Próximo a reemplazo'), ('mal_estado', 'Mal estado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='prestamoactivo',
            name='estado_al_salir',
            field=models.CharField(choices=[('buen_estado', 'Buen estado'), ('proximo_a_reemplazo', 'Próximo a reemplazo'), ('mal_estado', 'Mal estado')], max_length=30),
        ),
    ]
