# Generated by Django 5.0.14 on 2026-09-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_proveedor_origen'),
        ('tecnica', '0007_alter_activo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='stock_alerta',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='activo',
            name='stock_critico',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='activo',
            name='stock_optimo',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.CheckConstraint(check=models.Q(('stock_critico__lte', models.F('stock_alerta'))), name='chk_activo_critico_lte_alerta', violation_error_message='Los umbrales deben cumplir: crítico ≤ alerta ≤ óptimo.'),
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.CheckConstraint(check=models.Q(('stock_alerta__lte', models.F('stock_optimo'))), name='chk_activo_alerta_lte_optimo', violation_error_message='Los umbrales deben cumplir: crítico ≤ alerta ≤ óptimo.'),
        ),
    ]
