# Generated by Django 5.0.14 on 2026-09-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnica', '0008_activo_stock_alerta_activo_stock_critico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoactivo',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
