# Generated by Django 5.0.14 on 2026-09-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnica', '0011_alter_movimientoactivo_precio_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoactivo',
            name='no_boleta',
        ),
    ]
