# Generated by Django 5.0.14 on 2026-09-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnica', '0012_remove_movimientoactivo_no_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripciones extra del producto.', verbose_name='Descripción'),
        ),
    ]
